fail_fast: true
repos:
  - repo: local
    hooks:
      - id: package-codebase-lambda-layer
        name: package-codebase-lambda-layer
        entry: python scripts/cicd/lambda_layer.py -i codebase/ -o codebase_layer/ -n codebase
        language: system
        pass_filenames: false
      - id: wheel-codebase-module
        name: wheel-codebase-module
        entry: bash setup-whl.sh
        language: system
        pass_filenames: false
      - id: terraform-fmt
        name: terraform-fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
