repos:
  - repo: local
    hooks:
      - id: generate codebase whl
        name: generate-codebase-whl
        entry: python setup.py bdist_wheel
        language: system
        pass_filenames: false
      - id: generate documentation index
        name: generate-documentation-index
        entry: python scripts/cicd/generate_doc_index.py
        language: system
        pass_filenames: false
      - id: package-codebase-lambda-layer
        name: package-codebase-lambda-layer
        entry: python scripts/cicd/lambda_layer.py -i codebase/ -o infrastructure/lambda_layers/codebase/ -n codebase
        language: system
        pass_filenames: false
      - id: terraform-fmt
        name: terraform-fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
