fail_fast: true
repos:
  - repo: local
    hooks:
      - id: package-codebase-lambda-layer
        name: package-codebase-lambda-layer
        entry: python scripts/cicd/lambda_layer.py -i codebase/ -o infrastructure/lambda_layers/codebase/ -n codebase
        language: system
        pass_filenames: false
      - id: terraform-fmt
        name: terraform-fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
