source_name: "business_bank_config_jdbc_extract"
source_owners:
  - dirkscgm@gmail.com
extract:
  job_type: glue # emr, ecs
  source_type: jdbc # api, file
  script_name: jdbc_extract_job.py
  arguments:
    --test: 1
  default_arguments:
    num_partitions: "4"
    fetchsize: "1000"
    extract_type: "FE"
    worker_no: "2"
    worker_type: "Standard"
  db_engine: "postgres" # mysql
  db_secret: "postgres/mock_db"
  db_port: "5432"
  db_name: "fzmjfsta"
  tables: # this is the extract_table
    public.accounts:
      partition_column: "AccountID"
      lower_bound: "1"
      upper_bound: "1000"
      extract_type: "PE"
      hwm_col_name: "AccountID"
      hwm_column_type: "IntegerType"
      lwm_value: "1"
      hwm_value: "1000"
      repartition_dataframe: "true"
      extract_s3_partitions: "AccountType"
      # extract_s3_uri: Defined by the Step Function
      # num_partitions: Set as default above
      # fetchsize: Set as default above
      # reingest: Defined by the Step Function
      # tracking_table_name: Defined in the infrastructure
    public.other:
      partition_column: "AccountID"
      lower_bound: "1"
      upper_bound: "1000"
      hwm_col_name: "AccountID"
      hwm_column_type: "IntegerType"
      lwm_value: "1"
      hwm_value: "1000"
      repartition_dataframe: "true"
      extract_s3_partitions: "AccountType"
      # extract_s3_uri: Defined by the Step Function
      # num_partitions: Set as default above
      # fetchsize: Set as default above
      # reingest: Defined by the Step Function
      # tracking_table_name: Defined in the infrastructure
#transform:
#  job_type: glue # emr, ecs
#  script_name: jdbc_transform_job.py
#  arguments:
#    --test: 1
#load:
#  job_type: glue # emr, ecs
#  script_name: jdbc_load_job.py
#  arguments:
#    --test: 1